<?php
if (!defined('ABSPATH')) { exit; }
class WNM_Admin {
    private WNM_Repository $repo; private WNM_Bundle_Calculator $calculator;
    public function __construct(WNM_Repository $repo,WNM_Bundle_Calculator $calculator){$this->repo=$repo;$this->calculator=$calculator;}
    public function register(): void { add_menu_page('Woo NM Manager','Woo NM Manager','manage_woocommerce','woo-nm-manager',[$this,'render'],'dashicons-products',56); }
    public function render(): void {
        if(!current_user_can('manage_woocommerce')) wp_die('Forbidden'); $this->handlePost(); $bundles=$this->repo->getBundles(); $thresholds=$this->repo->getThresholds();
        $products=wc_get_products(['limit'=>-1,'status'=>['publish','private','draft'],'orderby'=>'name','order'=>'ASC']);
        echo '<div class="wrap"><h1>Woo NM Manager</h1><h2>Bundles / Kits</h2>';
        if(!$bundles) echo '<p>No bundles configured yet.</p>'; else { echo '<table class="widefat striped"><thead><tr><th>Bundle</th><th>Possible kits</th><th>Components</th><th></th></tr></thead><tbody>';
            foreach($bundles as $bundle){$bp=wc_get_product((int)$bundle['bundle_product_id']);$calc=[];$parts=[];foreach($bundle['components'] as $c){$p=wc_get_product((int)$c['product_id']);$stock=($p&&$p->managing_stock())?$p->get_stock_quantity():null;$calc[]=['stock'=>$stock,'required'=>(int)$c['qty']];$parts[]=$p?sprintf('%d × %s (stock: %s)',(int)$c['qty'],$p->get_name(),$stock===null?'not managed':$stock):'Missing product';}$possible=$this->calculator->possibleKits($calc);echo '<tr><td><strong>'.esc_html($bp?$bp->get_name():'Missing product').'</strong></td><td>'.esc_html($possible===null?'Unavailable':(string)$possible).'</td><td>'.esc_html(implode(' · ',$parts)).'</td><td><form method="post">';wp_nonce_field('wnm_delete_bundle');echo '<input type="hidden" name="wnm_action" value="delete_bundle"><input type="hidden" name="bundle_product_id" value="'.esc_attr($bundle['bundle_product_id']).'"><button class="button">Remove</button></form></td></tr>';}
            echo '</tbody></table>';}
        echo '<h2>Add / Update bundle</h2><form method="post">';wp_nonce_field('wnm_save_bundle');echo '<input type="hidden" name="wnm_action" value="save_bundle"><p><label>Bundle product <select name="bundle_product_id" required><option value="">Select</option>';$this->productOptions($products);echo '</select></label></p><table class="widefat" id="wnm-components"><thead><tr><th>Component</th><th>Qty / kit</th><th></th></tr></thead><tbody>';$this->componentRow($products);echo '</tbody></table><p><button type="button" class="button" id="wnm-add">Add component</button></p>';submit_button('Save bundle');echo '</form>';
        echo '<h2>Tracked products / Alerts</h2>';$ids=$this->repo->trackedProductIds();if(!$ids)echo '<p>Add bundle components first.</p>';else{echo '<form method="post">';wp_nonce_field('wnm_save_thresholds');echo '<input type="hidden" name="wnm_action" value="save_thresholds"><table class="widefat striped"><thead><tr><th>Product</th><th>Stock</th><th>Threshold</th><th>Status</th><th>Used in</th></tr></thead><tbody>';foreach($ids as $id){$p=wc_get_product($id);if(!$p)continue;$stock=$p->managing_stock()?$p->get_stock_quantity():null;$has=array_key_exists($id,$thresholds);$t=$has?(int)$thresholds[$id]:'';$status=(!$has||$stock===null)?'Not monitored':(((int)$stock<$t)?'Low stock':'OK');$names=[];foreach($this->repo->bundlesUsingProduct($id) as $bid){$b=wc_get_product($bid);if($b)$names[]=$b->get_name();}echo '<tr><td>'.esc_html($p->get_name()).'</td><td>'.esc_html($stock===null?'Stock not managed':(string)$stock).'</td><td><input type="number" min="0" name="threshold['.esc_attr($id).']" value="'.esc_attr($t).'" style="width:100px"></td><td>'.esc_html($status).'</td><td>'.esc_html(implode(', ',$names)).'</td></tr>';}echo '</tbody></table>';submit_button('Save thresholds');echo '</form>';}
        echo '</div>'; ob_start();$this->componentRow($products);$template=ob_get_clean();echo '<script>(()=>{const b=document.querySelector("#wnm-components tbody"),t='.wp_json_encode($template).';document.getElementById("wnm-add")?.addEventListener("click",()=>b.insertAdjacentHTML("beforeend",t));b?.addEventListener("click",e=>{if(e.target.classList.contains("wnm-remove"))e.target.closest("tr").remove()})})();</script>';
    }
    private function handlePost(): void {
        if($_SERVER['REQUEST_METHOD']!=='POST'||empty($_POST['wnm_action']))return;$a=sanitize_key(wp_unslash($_POST['wnm_action']));
        if($a==='save_bundle'){check_admin_referer('wnm_save_bundle');$bundle=absint($_POST['bundle_product_id']??0);$ids=array_map('absint',(array)($_POST['component_product_id']??[]));$qtys=array_map('absint',(array)($_POST['component_qty']??[]));$c=[];$seen=[];foreach($ids as $i=>$id){$q=max(1,$qtys[$i]??1);if(!$id||$id===$bundle||isset($seen[$id])||!wc_get_product($id))continue;$seen[$id]=1;$c[]=['product_id'=>$id,'qty'=>$q];}if($bundle&&wc_get_product($bundle)&&$c)$this->repo->saveBundle($bundle,$c);wp_safe_redirect(admin_url('admin.php?page=woo-nm-manager'));exit;}
        if($a==='delete_bundle'){check_admin_referer('wnm_delete_bundle');$this->repo->deleteBundle(absint($_POST['bundle_product_id']??0));wp_safe_redirect(admin_url('admin.php?page=woo-nm-manager'));exit;}
        if($a==='save_thresholds'){check_admin_referer('wnm_save_thresholds');$t=[];foreach((array)($_POST['threshold']??[]) as $id=>$v)$t[absint($id)]=max(0,absint($v));$this->repo->saveThresholds($t);wp_safe_redirect(admin_url('admin.php?page=woo-nm-manager'));exit;}
    }
    private function productOptions(array $products): void { foreach($products as $p)echo '<option value="'.esc_attr($p->get_id()).'">'.esc_html($p->get_name().($p->get_sku()?' ['.$p->get_sku().']':'')).'</option>'; }
    private function componentRow(array $products): void { echo '<tr><td><select name="component_product_id[]" required><option value="">Select</option>';$this->productOptions($products);echo '</select></td><td><input type="number" min="1" value="1" name="component_qty[]" required></td><td><button type="button" class="button wnm-remove">Remove</button></td></tr>'; }
}
